### ISSUE TITLE
DETALLE DE FICHA TECNICA, CORRECCION DE LA VISTA PARA EL PDF

### ISSUE THREAD

**Issue by REIMOC96** [felipecastillo-b/mercy_developer#1]
Me di cuenta que hay un par de detalles que tener en cuenta en mi PDF final de descarga y envió, es una corrección en la vista que se usa para generar estos PDF, no se muestra en la descarga ni el correo el antivirus ni el navegador que esta instalado en el pc, corregí esto en mi proyecto personal, copiar el contenido del archivo "FichaToPDF.cshtml" se omitió la sección de la tabla:

![Sin título](https://github.com/user-attachments/assets/ef8eb8a1-bfb7-4702-bad6-fbf770af6eae)

Corrección en el enlace : 

https://github.com/REIMOC96/Mercy_developer_FINAL/blob/main/MercDevs_ej2/Views/Datosfichatecnicas/FichaToPdf.cshtml

Imagen de Referencia de la corrección:

![Sin títul2o](https://github.com/user-attachments/assets/60ca9c34-508f-40b6-a9c3-d04f31cb8ea0)

**Comment by felipecastillo-b** [comment]
Hola,

Quiero informarte que ya he resuelto el problema relacionado con la vista para el PDF. He corregido el error que impedía mostrar el antivirus y el navegador instalados en el PC, tanto en la vista, descarga del PDF y en el PDF que se adjunta al correo.

Agradezco tu paciencia y el tiempo que tomaste para señalar el problema. Puedes revisar la corrección en el siguiente enlace:

[Enlace a la corrección](https://github.com/felipecastillo-b/mercy_developer/commit/527cbc73facd58e431f2e21f4ef0fce808ba6b12)

![VistaFichaTecnica_corregida](https://github.com/user-attachments/assets/2ecd5732-0cde-4ae8-80a1-b95ac63885f8)

¡Gracias de nuevo!
